### ISSUE TITLE
Use the vault service for the kubecf pipelines

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#1047]
## Acceptance Criteria

- all pipelines for the kubecf ci use the vault service as a source of secrets.

**Comment by viovanov** [comment]
Blocked by #1045

**Comment by viovanov** [comment]
This ticket is about using the vault action in the kubecf github actions pipeline

**Comment by andreas-kupries** [comment]
To fill things in, we are talking about

  - `.github/workflows/conventional-commits-lint.yml`
  - `.github/workflows/pull-request-ci.yaml`
  - `.github/workflows/pull-request-queue.yaml`

in this repository. The secrets currently used by these flows are

  - `secrets.GITHUB_TOKEN` (alt: `secrets.github_token` ?! (both forms are used))
  - `secrets.GH_BOT_TOKEN`
  - `secrets.GKE_CRED_JSON`

For the first two we have multiple possibilities, all in `secret/data/kubecf`:

  - `github.cfcontainerizationbot-labeler-personal-access-token`
  - `github-access-token`
  - `github-limited-token`

@viovanov, @mook-as Do you know the relevant mapping ?

The last item on the other hand is trivial, it maps to `secret/data/cloud-providers`, key `gke.GKE_CRED_JSON`.

**Comment by andreas-kupries** [comment]
Note, further: The vault action will need the VAULT_TOKEN (same as we did for pxc-docker).
I do not have the ability to add a GHA secret for that to this repo.

**Comment by mook-as** [comment]
`secrets.GITHUB_TOKEN` is the same as `github.token`, which is supplied by GitHub Actions and we don't have to do anything about it.

I don't know about the other ones; as we can't dig it out of the GitHub secrets UI, we'll need to look at their use to fix things.  I suspect the one in `pull-request-queue.yaml`, for example, should map to `cfcontainerizationbot-labeler-personal-access-token` (because it adds a label to the PR).

**Comment by andreas-kupries** [comment]
Thank you, that was exactly what I was looking for.
