### ISSUE TITLE
Include the Eirini, EiriniX and Bits templates in KubeCF

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#1179]
**Is your feature request related to a problem? Please describe.**
These charts are not being used on their own by anyone.
Using subcharts is harder than just having templates in the main KubeCF chart.

**Describe the solution you'd like**
Include all template in the KubeCF chart.
Make sure to keep the namespaced value keys, so we don't break compatibility.

**Comment by jandubois** [comment]
I want to work on this because I have some thoughts on how to structure the repo layout to support "addon" or "mixin" templates, based on the work I've been doing restructuring our config mechanism for the multi-stack support.

I'm not ready to start work on it right now, but have assigned to myself already. I will update this issue with more info in the next 2 days.

**Comment by andreas-kupries** [comment]
:warning: Ticket #792 and its PRs #1022 (+ drafts #1182, #1185) becomes moot due to this.
:warning: If we make sure that what we want from #792 is done in the work for this ticket as well.
