### ISSUE TITLE
Update nginx SUSE buildpack

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#1263]
## Acceptance Criteria

- nginx buildpack is updated to its latest version

**Comment by thardeck** [comment]
The reason why the brats are failing is because nginx wants to log to `/dev/stdout` but has no access there anymore.

```
           Downloading app package...
           Downloaded app package (2K)
           -----> Nginx Buildpack version fvgxfx
           -----> Supplying nginx
           -----> Requested nginx version: 1.19.2 => 1.19.2
           -----> Installing nginx 1.19.2
                  Copy [/tmp/buildpacks/a02d5e9f57175274040ab8687209b4d6/dependencies/cb0c6c7b8e7ec4a08619b7defb90c8d3/nginx-1.19.2-linux-x64-sle15-541df31a.tgz]
           nginx: the configuration file /tmp/conf254160206/nginx.conf syntax is ok
           2020/08/28 08:31:04 [emerg] 30#0: open() "/dev/stdout" failed (13: Permission denied)
           nginx: configuration file /tmp/conf254160206/nginx.conf test failed
                  **ERROR** Could not validate nginx.conf: nginx.conf contains syntax errors: exit status 1
           Failed to compile droplet: Failed to run all supply scripts: exit status 14
           Exit status 223
```

**Comment by thardeck** [comment]
I can push the brats test application fine in kubecf 2.4.0 setup with catapult so it might be related to our brats cluster.

**Comment by fargozhu** [comment]
it will be finished when #1262 is closed.

**Comment by thardeck** [comment]
The issue does not happen with GKE so it might be Caasp related - but does not have too since Kind and GKE were setup by catapult.

Since we are planning to run the brats on public cloud in the future it is not worth debugging much I suppose - unless @fargozhu  thinks differently because it might be of course be relevant for customers running kubecf on Caasp.

To reproduce you can use the fixture test app: https://github.com/SUSE/cf-nginx-buildpack/tree/master/fixtures/brats

**Comment by thardeck** [comment]
Anyway, the SUSE Nginx buildpack 1.1.15.1 is released: https://github.com/SUSE/cf-nginx-buildpack/releases/tag/v1.1.15.1

**Comment by jandubois** [comment]
Why is this closed? The buildpack is not updated in the `master` branch of `chart/config/sle15.yaml`, and there is no pending PR for updating it either.
