### ISSUE TITLE
Split locket into a separate pod

### ISSUE THREAD

**Issue by andrew-edgar** [cloudfoundry-incubator/kubecf#1410]
**Is your feature request related to a problem? Please describe.**
Diego-api pod has both BBS and locket.  The bbs is currently only talking using 127.0.0.1 which is not standard and causes custom certs to be created for kubecf to add that as an alternative name.   

There is no reason locket and bbs should be in the same pod and would allow them to be more separate and make this issue https://github.com/cloudfoundry-incubator/kubecf/issues/25 also work better.

**Describe the solution you'd like**
Have locket a separate pod from Diego-api

**Describe alternatives you've considered**
Need to add 127.0.0.1 to the locket certs when this is not defined in cf-deployment.

**Comment by andrew-edgar** [comment]
With more investigation this is worse than I thought!   Right now `locket.service.cf.internal` will ONLY return the "active" diego-api.  This is incorrect.   locket server is not active/passive.  it is active/active and should as long as the locket container is running this DNS needs to return all of the diego-apis.

This is bad because we are no longer balancing this locket server load.  in a larger env we are stuck sending all locket requests to the same pod.  Which is poor use of resources.   I think this should be up the priority list as this is a regression from how bosh works for the locket server.

**Comment by jandubois** [comment]
I'm in favour of this change. It is pretty much the same reason we split `routing-api` away from the `api` instance group, so `api` could be active/active while `routing-api` is active/passive.

And as already mentioned, it helps with Eirini: we can get rid of `bbs` and `silk-controller` jobs, and have `locket` in an instance group that doesn't have `diego` in its name.

I would prefer to do this using the quarks-specific `qmove` op instead of doing all the manual deployment manifest editing we do at build time currently. That would require https://github.com/cloudfoundry-incubator/quarks-operator/issues/1122 to be completed though; otherwise `scripts/image_list.rb` is going to break.

According to the Quarks team tracker this is scheduled for the sprint at the end of the month, but given that they dealt with a lot of unscheduled work lately, I suspect this might slip a bit. I would still prefer to wait for that.
