### ISSUE TITLE
Use active/passive probes where required

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#309]
**Is your feature request related to a problem? Please describe.**
Right now we're splitting off some jobs from instance groups, because they are active/passive.
The CF Operator now supports this capability, so we no longer have to do that.

**Describe the solution you'd like**
Use the cf-operator active passive probes to support this scenario.
See [this document](https://github.com/cloudfoundry-incubator/cf-operator/blob/34518eb38a2a8c2ae52eec3eb6b43d4ab98d5634/docs/controllers/quarks_statefulset.md#quarksstatefulset-active-passive-controller) for more details.

**Describe alternatives you've considered**
Keeping the current solution.
This takes us away from our goal of being as close as possible to cf-deployment.

**Additional context**
n/a

**Comment by fargozhu** [comment]
blocked by https://www.pivotaltracker.com/n/projects/2192232/stories/170883970.

**Comment by jimmykarily** [comment]
Development happens here: https://github.com/jimmykarily/cf-operator/tree/aduffeck/active-passive-probes (Since I don't have push access to teh cf-operator repo). 

- Added code to parse the active/passive probe form the deployment manifest. 
- Fixed bug to only run the probe on the correct pods (not every pod).
- Added a selector to the generated services to only route traffic to the pods that are marked as "active".

We are now testing the changes on kubecf.
