### ISSUE TITLE
PRs to fix patches in *routing-api* upstream project

### ISSUE THREAD

**Issue by fargozhu** [cloudfoundry-incubator/kubecf#521]
./api/routing-api/bpm/patch_bpm.sh

**Comment by fargozhu** [comment]
relates with #12

**Comment by andreas-kupries** [comment]
This should be marked blocked and a ticket added to confirm that
- the patch is still relevant, and
- that we do not have a fix in SCF which was simply not ported over to kubecf, and
- that we do not have an operator based solution for the problem. This last point is a more concrete form of the first point.

**Comment by andreas-kupries** [comment]
Or do the checks as part of this ticket.

**Comment by mook-as** [comment]
[The relevant patch](https://github.com/cloudfoundry-incubator/kubecf/blob/master/bosh/releases/pre_render_scripts/routing-api/routing-api/bpm/patch_bpm.sh) (I am not sure why we never linked it) changes the BPM command to not use `spec.ip` because quarks-operator implements process management differently: BPM is rendered from a _completely different_ container (and therefore has no chance of having a valid `spec.ip`.

Unfortunately I'm not sure how we can implement the patch in an upstream-compatible way: we hack around things by changing the `POD_IP` environment variable via [an ops file](https://github.com/cloudfoundry-incubator/kubecf/blob/5a53d454c26d24378a5689fc50e9c3536eafa01a/deploy/helm/kubecf/assets/operations/instance_groups/routing-api.yaml#L8-L12), which wouldn't make any sense in the BOSH VM world.

**Comment by andreas-kupries** [comment]
I agree that this patch is both required, and not upstreamable.
And big thanks to @mook-as  for looking deeper into this.

**Comment by andreas-kupries** [comment]
Action: Created PR #1070 adding info to the patch on why it was not upstreamed. This ticket is done.
