### ISSUE TITLE
Ability to use an external blobstore

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#563]
**Is your feature request related to a problem? Please describe.**
Included blobstore is a spof. 

**Describe the solution you'd like**
Use upstream ops files to enable switching to an external provider.

**Describe alternatives you've considered**
#138 

**Additional context**
Blocks #200

**Comment by bikramnehra** [comment]
From @qu1queee:
- PR same https://github.com/cloudfoundry-incubator/kubecf/pull/138, but with a new branch that is up-to-date with master branch.
- We need to expose this ones in the kubecf values.yml https://github.com/cloudfoundry-incubator/kubecf/blob/master/deploy/helm/kubecf/assets/operations/instance_groups/eirini.yaml#L151-L153 , because of https://github.com/cloudfoundry-incubator/kubecf/pull/138#discussion_r348036228.
- We need a aws s3 bucket, inside IBM we already have this working, but we use an s3 compatible one, not the AWS one. So I dont have an AWS bucket now, I need to get one first, to test the future PR.

So I will be creating a feature branch rebasing https://github.com/cloudfoundry-incubator/kubecf/pull/138 onto `master` and also try to fix the Eirini issues. Once we have the changes we probably would need an AWS S3 bucket to test them.

**Comment by bikramnehra** [comment]
@qu1queee correct me if I am wrong:-

It seems like the [fix](https://github.com/cloudfoundry-incubator/eirini-staging/pull/9) for CA trust [issue](https://www.pivotaltracker.com/n/projects/2172361/stories/169707308) has been merged and following images were generated:
https://github.com/cloudfoundry-incubator/eirini-release/commit/0f4732abed7d72e5a6f8a63ae70b8dcbeb31701f

Since there is no release of [eirini-staging](https://github.com/cloudfoundry-incubator/eirini-staging/releases) after `0.3.0` hence no images therefore we might have to reference those images via their SHA commit: https://github.com/cloudfoundry-incubator/kubecf/pull/608. We need to check if `eirini` deployment works with these images on CI.

**Comment by bikramnehra** [comment]
Noticing following issue while using any region in `s3` config other than the default `us-east-1`:

`IllegalLocationConstraintException</Code><Message>The unspecified location constraint is incompatible for the region specific endpoint this request was sent to.`

It seems like that the [aws_region](https://github.com/cloudfoundry-incubator/kubecf/pull/608/files#diff-8fc2de7ef5a3d25ddfce0cd023890d0cR264) is somehow not being passed by the CC while creating the specified s3 bucket. 

```
{"timestamp":1586201434.5484383,"message":"Error with blobstore: Excon::Error::BadRequest - Expected(200) <=> Actual(400 Bad Request)\nexcon.error.response\n  :body          => \"<?xml version=\\\"1.0\\\" encoding=\\\"UTF-8\\\"?>\\n<Error><Code>IllegalLocationConstraintException</Code><Message>The unspecified location constraint is incompatible for the region specific endpoint this request was sent to.</Message><RequestId>9C8477F680772391</RequestId><HostId>rHCPsRnpiW7XYnEYaaC+YwRBIhP4Zx7oIrHEF0058/jIQgelw1Z1PA8JDtoxPglQTOc6oFF9bJo=</HostId></Error>\"\n  :cookies       => [\n  ]\n  :headers       => {\n    \"Connection\"       => \"close\"\n    \"Content-Type\"     => \"application/xml\"\n    \"Date\"             => \"Mon, 06 Apr 2020 19:30:34 GMT\"\n    \"Server\"           => \"AmazonS3\"\n    \"x-amz-id-2\"       => \"rHCPsRnpiW7XYnEYaaC+YwRBIhP4Zx7oIrHEF0058/jIQgelw1Z1PA8JDtoxPglQTOc6oFF9bJo=\"\n    \"x-amz-request-id\" => \"9C8477F680772391\"\n  }\n  :host          => \"kubecf-buildpacks-cf.s3-us-west-2.amazonaws.com\"\n  :local_address => \"172.17.0.15\"\n  :local_port    => 43720\n  :path          => \"/\"\n  :port          => 443\n  :reason_phrase => \"Bad Request\"\n  :remote_ip     => \"52.218.246.209\"\n  :status        => 400\n  :status_line   => \"HTTP/1.1 400 Bad Request\\r\\n\"\n","log_level":"error","source":"cc.error_handling_client","data":{},"thread_id":47293876479480,"fiber_id":47293941472300,"process_id":66,"file":"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/lib/cloud_controller/blobstore/fog/error_handling_client.rb","lineno":63,"method":"rescue in error_handling"}
```
```
{"timestamp":1586201434.5567675,"message":"Buildpack staticfile_buildpack failed to install or update. Error: #<CloudController::Blobstore::BlobstoreError: Expected(200) <=> Actual(400 Bad Request)\nexcon.error.response\n  :body          => \"<?xml version=\\\"1.0\\\" encoding=\\\"UTF-8\\\"?>\\n<Error><Code>IllegalLocationConstraintException</Code><Message>The unspecified location constraint is incompatible for the region specific endpoint this request was sent to.</Message><RequestId>9C8477F680772391</RequestId><HostId>rHCPsRnpiW7XYnEYaaC+YwRBIhP4Zx7oIrHEF0058/jIQgelw1Z1PA8JDtoxPglQTOc6oFF9bJo=</HostId></Error>\"\n  :cookies       => [\n  ]\n  :headers       => {\n    \"Connection\"       => \"close\"\n    \"Content-Type\"     => \"application/xml\"\n    \"Date\"             => \"Mon, 06 Apr 2020 19:30:34 GMT\"\n    \"Server\"           => \"AmazonS3\"\n    \"x-amz-id-2\"       => \"rHCPsRnpiW7XYnEYaaC+YwRBIhP4Zx7oIrHEF0058/jIQgelw1Z1PA8JDtoxPglQTOc6oFF9bJo=\"\n    \"x-amz-request-id\" => \"9C8477F680772391\"\n  }\n  :host          => \"kubecf-buildpacks-cf.s3-us-west-2.amazonaws.com\"\n  :local_address => \"172.17.0.15\"\n  :local_port    => 43720\n  :path          => \"/\"\n  :port          => 443\n  :reason_phrase => \"Bad Request\"\n  :remote_ip     => \"52.218.246.209\"\n  :status        => 400\n  :status_line   => \"HTTP/1.1 400 Bad Request\\r\\n\"\n>","log_level":"error","source":"cc.background","data":{},"thread_id":47293876479480,"fiber_id":47293941472300,"process_id":66,"file":"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/app/jobs/runtime/create_buildpack_installer.rb","lineno":25,"method":"rescue in perform"}
```

**Comment by bikramnehra** [comment]
filed: https://github.com/cloudfoundry-incubator/kubecf/issues/656 for investigation the above issue.
