### ISSUE TITLE
I'd like to re-run tests for a PR by leaving a comment on that PR's discussion thread

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#628]
**Is your feature request related to a problem? Please describe.**
To re-run tests I have to pin and un-pin on Concourse, and it's error prone, and hard.

**Describe the solution you'd like**
Person with write access to the repo leaves a comment like "test please", and the PR head commit is scheduled to be tested.

**Describe alternatives you've considered**
Pin and unpin and Pin and unpin and Pin and unpin and Pin and unpin and Pin and unpin and Pin and unpin and Pin and unpin and Pin and unpin and Pin and unpin.

**Comment by viovanov** [comment]
See https://probot.github.io/docs/webhooks/

**Comment by f0rmiga** [comment]
I've heard this idea before. Ping @mook-as

**Comment by mook-as** [comment]
I still believe in not putting in bot-directed and bot-originated comments, since mixing communication methods is painful.  I'd prefer something like a `CI: Queued` label the PR that the bot would automatically remove once the branch arrives in CI, so that re-triggering is 2-click (once to show the Labels list, and once to select the label).  Or do it with some fancy REST API call / CLI if you prefer.  That's few buttons than typing out all of `test please` :D Also, that means you can't queue a second run _before_ the first run has landed in CI (but, depending on how we implement it, might be able to queue it before the first run _completes_)…

(And, yes, `issues` has a `labeled` [event](https://developer.github.com/v3/activity/events/types/#issuesevent).)

Labels would not work as well if we have more fine-grained configuration (e.g. if we want to say "only run CATS, not any of the other test suites").

**Comment by fargozhu** [comment]
@viovanov closing this issue since we decided to move quickly to the GHA.
