### ISSUE TITLE
CI: move back Eirini smoke test to prod job

### ISSUE THREAD

**Issue by mudler** [cloudfoundry-incubator/kubecf#672]
**Is your feature request related to a problem? Please describe.**
Due to HW problems in CI, we moved the Eirini smoke test to no-prod jobs https://concourse.suse.dev/teams/main/pipelines/kubecf?group=no-prod.

**Describe the solution you'd like**
Now the CI runs stable again, we could move the Eirini job among the prod ones, see : https://concourse.suse.dev/teams/main/pipelines/kubecf/jobs/smoke-tests-eirini

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by viccuad** [comment]
Is it needed to bump smoke tests to consume https://github.com/cloudfoundry/cf-smoke-tests/pull/61 ?
Without it, smokes on Eirini on sle15 stack will fail.

**Comment by jandubois** [comment]
Smoke tests have already been bumped in #920 and cherry-picked to `release-2.2` in #921

However, eirini smoke tests on the `release-2.2` pipeline are still completely red due to some logging problem:

https://concourse.suse.dev/teams/main/pipelines/kubecf/jobs/smoke-tests-eirini-release-2.2/builds/9

The eirini-smoke test is already on the non-experimental tab for each pipeline; it is just not configured as a required tests on Github for gating PRs right now.

So isn't this card already done? Fixing the failure of eirini smoke tests themselves is an independent issue.

**Comment by mook-as** [comment]
Hmm, that particular build looked like the OOM issue:

> Waiting for app to start...
Start unsuccessful
⋮
   2020-05-26T05:55:16.32+0000 [API/0] OUT Process has crashed with type: "web"
   2020-05-26T05:55:16.33+0000 [API/0] OUT App instance exited with guid ae09e5c9-8647-47dc-a506-de6b2bdac833 payload: {"instance"=>"smokes-10-app-c22275445dc25749-smoke-10--92a2b044e7-0", "index"=>0, "cell_id"=>"", "reason"=>"**OOMKilled**", "exit_status"=>137, "exit_description"=>"OOMKilled", "crash_count"=>0, "crash_timestamp"=>14, "version"=>"66088a94-a076-4a59-806f-f8c8e5fd3127"}

It only looked like a logging issue because the first test setup was to check for logging.

However, it does look like it has the bump for smoke tests: it is using [smoke-tests-release 40.0.128](https://github.com/cloudfoundry-incubator/kubecf/blob/40b13219f1f462cc51dfe1b12d3ec0e657d5c30d/deploy/helm/kubecf/values.yaml#L52), which should be using the [sources](https://github.com/cloudfoundry/cf-smoke-tests-release/tree/40.0.128/src) with the appropriate [merge](https://github.com/cloudfoundry/cf-smoke-tests/commit/4d395b6bf089b4650742570ab6391dd315b1dba4).

**Comment by jandubois** [comment]
This is weird, the OOM error is fixed on `master`, but still seems to happen on `release-2.2` even though the bump to `smoke-tests-release` has been merged.

**Comment by viovanov** [comment]
This is done
