### ISSUE TITLE
spike: sharded clusters control plane/cells on IKS

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#822]
**Is your feature request related to a problem? Please describe.**
See if the topology described here is possible
https://docs.google.com/drawings/d/17YSMul7DEk0WFT6UnSsQqJnJJkgWUWxr7VbpMndQcZI

**Describe the solution you'd like**
Figure out if communication can happen the way described in the docs.
Spike to see if we can break up the control plane from the cells using ops files.

**Comment by jandubois** [comment]
Can you explain why this topology is desirable?

Is this supposed to be a multi-zone or multi-region configuration?

If this is just a way to separate the control plane from the worker nodes, can't you achieve the same effect with node taints and tolerations instead (the same way user pods are kept away from kube master nodes)? That way you don't need cross-cluster networking.

**Comment by bkrannich** [comment]
@viovanov: As mentioned, I took a look at this Github issue. Here is my feedback:

I think as long as we are talking "classical" CF architecture (gorouter, Diego, etc.) you'll
  * have to deploy a set of technologies into your remote cluster and
  * have the routing tier support this distributed setup
Especially for the latter, the question is if the VMWare routing team will invest.

On the cf-for-k8s side, I think you get by with less infrastructure and the routing tier is somewhat entangled with where the apps run - which is a blessing and a curse at the same time:
* a blessing because you don't need to "hop" between K8s clusters to receive and dispatch requests to CF apps
* a curse because it means that having Istio on the cluster running your CF apps is mandatory for now

In my ideal picture, I'd love to see the requirement for having Istio co-deployed go away because this would result in a deployment layout where one would have a clear separation between "the control plane" (which could run on a cluster that a customer would not even see [apart from login in to it's CF API]) and "the data plane" which would be "pure" K8s workloads that can even exist when the control plane is not available plus a possibility to say: "Ok, as these are pure K8s workloads, put whatever else you like on this cluster, it's yours anyhow". So, having the CF control plane more as an additional means to bring workloads to a cluster than an actual "part of the running system".

**Comment by viovanov** [comment]
@bkrannich 

For classical:

- you mean like calico or cilium? this is usually available on kubernetes offerings (SUSE's CaaSP comes with cilium, on IBM IKS there's calico); these should be solutions to make the clusters talk to each other, and I assume they're already there, at the Kube level, and not part of KubeCF
- I don't think there are any changes required to the CF routing components - almost done with a spike on this, will let you know if this turns out to be 100% true, but looking good so far

For native:

Depending on your requirements (you might want to use the multi-cluster setup to provide geo redundancy), you still need that extra hop anyway, I don't think we should get rid of it.

**Comment by viovanov** [comment]
This spike was a success. 🍏

Was able to run a control plane installation of kubecf without a diego cell on one cluster, and just diego cells on another cluster.

Both kube clusters were deployed on IBM IKS, and they used a setup that allows pod and service communication across clusters in the same PVC [1].

The deployment also used isolation segments. With all services and secrets configured properly, everything connected properly and an app was deployed. Traffic routed to the application correctly.

The following stories were created to support this in kubecf:
#934, #935, #936, #938, #939, #940 
The following quarks operator bug was discovered during the spike:
https://www.pivotaltracker.com/story/show/172993878

[1] https://archive.istio.io/v1.0/docs/examples/multicluster/icp/

**Comment by smoser-ibm** [comment]
@viovanov @qu1queee and everyone involved: thanks a lot for this awesome spike! Really, really great

**Comment by bkrannich** [comment]
@viovanov, @smoser-ibm: Maybe one thing I totally missed to ask: Now that you have shown that this distribution works, what would you do with it? 😃

**Comment by smoser-ibm** [comment]
maybe migrate a huge bosh-based deployment starting very soon (before cf4k8s is ready) ? @bkrannich (and then do a 2nd migration to CF4K8s once Eirini scales to the required levels

**Comment by bkrannich** [comment]
@smoser-ibm: That's why I'm asking: Would you take a huge BOSH-based deployment and map it to a set of Diego cells on one K8s cluster? Or would that come with something like one K8s cluster per Isolation Segment? And if it's the latter, would you be confident to be able to keep the same overall system size even if parts run on K8s?

**Comment by smoser-ibm** [comment]
@bkrannich All Diego cells to *one* cluster ? No. That's exactly why we did this spike - to be able to spread the deployment across many clusters. This might or might not use isolation segments - those were not our primary concern. The primary concern was: Can we split a deployment such that we have one (multi-zone) cluster for the control plane, and then let's say 3-5 Clusters for the "cells". 
With that, we're hoping to be able to  keep the same overall system size - but that's the next experiment

**Comment by viovanov** [comment]
thanks for pointing that out @zrob - will take a look

**Comment by viovanov** [comment]
The spike is complete, we have support for multi-cluster deployments in kubecf now.
