### ISSUE TITLE
Upgrade test should be green

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#838]
**Describe the bug**
Upgrade test for diego is not currently green.

**Expected behavior**
Should be green.

**Environment**
CI

**Comment by mook-as** [comment]
I assume this is referring to [upgrade-test-master](https://concourse.suse.dev/teams/main/pipelines/kubecf/jobs/upgrade-test-master)? It looks like it's been green-ish recently; since same day this was filed actually.  It's currently failing, so we can fix that I guess?

**Comment by andreas-kupries** [comment]
The recent failures complain about unknown clusters in the `cleanup-cluster` part of `upgrade`.

```
10:37:42
	
ERROR: (gcloud.container.clusters.delete) Some requests did not succeed:
10:37:42
	
 - args: [u"ResponseError: code=404, message=Not found: projects/suse-225215/zones/europe-west3-c/clusters/kubecf-ci-0-0-92.\nNo cluster named 'kubecf-ci-0-0-92' in suse-225215."]
10:37:42
	
   exit_code: 1
10:37:42
	
   message: ResponseError: code=404, message=Not found: projects/suse-225215/zones/europe-west3-c/clusters/kubecf-ci-0-0-92.
10:37:42
	
No cluster named 'kubecf-ci-0-0-92' in suse-225215.
```

**Comment by andreas-kupries** [comment]
Ok. Having found the actual pipeline definition now (Thought it was in `cap/cap-ci`. It actually is the apparently new `kubecf/.concourse/` hierarchy I begin to understand a bit more.

The upgrade task and script is actually creating its own cluster, independent of the other parts of the pipeline. The cluster info is pushed into the `semver.gke-cluster` resource so that the ensured `cleanup-cluster` task has access to the information when it runs.

The main problem I currently have with the task script is that any and all logging is disabled, both the for the script itself, and for the underlying catapult actions (`QUIET_OUTPUT=true`).

That is the reason why the failed task has the unhelpful log of

```
Running the upgrade test
```

Yes, that is the entire log.

So, this limitation is the first thing which has to go, to see where it actually fails. From the fact that the cleanup task reports `No cluster named 'FOO' in suse-225215.` I would think that the failure is before cluster creation, or in cluster creation.

**Comment by andreas-kupries** [comment]
With activated log we see

```
 + echo 'Running the upgrade test'
 Running the upgrade test
 ++ cat kubecf-github-release/version
 + KUBECF_LATEST_RELEASE=2.2.1
 + export KUBECF_LATEST_RELEASE
 + export SCF_CHART=https://github.com/cloudfoundry-incubator/kubecf/releases/download/v2.2.1/kubecf-bundle-v2.2.1.tgz
 + SCF_CHART=https://github.com/cloudfoundry-incubator/kubecf/releases/download/v2.2.1/kubecf-bundle-v2.2.1.tgz
 + export ENABLE_EIRINI=false
 + ENABLE_EIRINI=false
 + export SCF_OPERATOR=true
 + SCF_OPERATOR=true
 + export FORCE_DELETE=true
 + FORCE_DELETE=true
 + export HELM_VERSION=v3.1.1
 + HELM_VERSION=v3.1.1
 + export BACKEND=imported
 + BACKEND=imported
 + export QUIET_OUTPUT=false
 + QUIET_OUTPUT=false
 ++ sed y/./-/ semver.gke-cluster/version
 + GKE_CLUSTER_NAME=kubecf-ci-0-0-177
 + export GKE_CLUSTER_NAME
 ++ readlink --canonicalize /root/.kube/config
 + KUBECFG=
```

So, kube config is directed to a non-existent path. 
The execution terminates on the `readlink` failing to find the path.

**Comment by andreas-kupries** [comment]
Fixed. Next stop: The attempted use of concourse key subst inside a script. Changing that over to a task parameter.

**Comment by andreas-kupries** [comment]
It is becoming clear that the `upgrade.sh` script was created from script code which existed at pipeline level and then was moved into a file without doing any adaption to the new environment. I.e. the concourse templating was left in, as was gomplate templating. :exasperation: (no icon for that, le sigh). I will watch the current iteration which should fix (i.e. eliminate) the concourse templating, and then cd. The gomplate templating will be squashed tomorrow. At least then I will know what I am doing from the very beginning.

**Comment by andreas-kupries** [comment]
The Friday EOD state resulted in a green task. Collapsed history now to be cleaner, then redo, to affirm that state.

**Comment by andreas-kupries** [comment]
PR = https://github.com/cloudfoundry-incubator/kubecf/pull/925
