### ISSUE TITLE
On cluster restart, uaa does not come back

### ISSUE THREAD

**Issue by f0rmiga** [cloudfoundry-incubator/kubecf#852]
**Describe the bug**

Restarting a kind cluster breaks UAA:

```
# bosh-pre-start-uaa container
+ '[' -x /var/vcap/jobs/uaa/bin/pre-start ']'
+ /var/vcap/jobs/uaa/bin/pre-start
[2020-05-11 20:11:46.993] uaa-pre-start - Starting
[2020-05-11 20:11:46.997] uaa-pre-start - Trying to run update-ca-certificates...
Unknown option: certbundle


real	0m0.025s
user	0m0.018s
sys	0m0.007s
```

**To Reproduce**

- Install KubeCF on kind.
- Stop the kind k8s worker node container.
- Start it again.
- Check that UAA gets the message above.

**Expected behaviour**

Not to fail.

**Comment by mook-as** [comment]
This _should_ be handled as part of the [uaa patch](https://github.com/cloudfoundry-incubator/kubecf/blob/91ce8d9eb645e98c59f5cd26d04efbc257df752b/bosh/releases/pre_render_scripts/uaa/uaa/jobs/patch_pre-start.sh) (at least, that's where `certbundle` would have came from).  I have not checked to see if we're failing to re-patch or something like that.

**Comment by andreas-kupries** [comment]
Note that we are currrently upstreaming this patch.
See ticket #507 and PR https://github.com/cloudfoundry/uaa-release/pull/197

**Comment by mook-as** [comment]
Reproduced on minikube:
1. Deploy as normal.
2. `minikube ssh -- systemctl restart docker.service`
3. 🔥

Looking into fixing now.

**Comment by mook-as** [comment]
Okay, so with some debugging, it looks like what happened was:
1. The pod restarts; the mounts are kept (including the patched file, and the patch sentinel)
2. `cf-operator util template-render` renders the ERB templates (un-patching the file)
3. Our patch script [sees the sentinel file](https://github.com/cloudfoundry-incubator/kubecf/blob/91ce8d9eb645e98c59f5cd26d04efbc257df752b/bosh/releases/pre_render_scripts/uaa/uaa/jobs/patch_pre-start.sh#L7) and skips patching.

We _used_ to do something like `patch --force`; I'll need to dig through history to see why we stopped. (Thulio thinks it might be because it returns an error when the file already patched.)
