### ISSUE TITLE
Look into speeding up image_list.json creation

### ISSUE THREAD

**Issue by mook-as** [cloudfoundry-incubator/kubecf#868]
**Is your feature request related to a problem? Please describe.**
Currently the image list creation takes a long time (~5 minutes on my machine); this is because it's trying all combinations of features.  Doing only the default combination takes ~0 seconds. (Note that when I tested locally, only doing the initial combination get all the images I needed — the output with any other combination didn't result in more images.)

**Describe the solution you'd like**
I'd like us to spike on ways to improve this.  Initial ideas:
- Spawn subprocesses to at least do _some_ runs in parallel.
- See if we can be smarter about what combinations to use.
- Do this only for release builds? (Might not be such a great idea.)

**Describe alternatives you've considered**
Haven't thought hard about that yet.

**Additional context**
See also #865 — this is being an issue on CI too.

**Comment by jandubois** [comment]
> * Do this only for release builds? (Might not be such a great idea.)

Why not? I'm not aware of *anything* we do with this list until we actually release.

I assume it is being used to copy images from the staging registry to the release registry.

And it is being used to facilitate air-gap installs to provide a list of images to make available locally.

So creating this list on every build would only serve a single purpose: make sure the script doesn't crash due to changes in the helm chart. But there is no way we would validate the output of the script. So getting the error on the first RC attempt still seems timely enough.

Of course finding a way to create a correct list in a reasonably short amount of time is still preferable.

**Comment by mook-as** [comment]
Closing as #965 should have sped things up quite a lot. @jandubois please reopen if you think that's inadequate.
