### ISSUE TITLE
Stable CI

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#883]
- [x] systemd unit to run a concourse worker
- [x] heat template for concourse workers
- [x] docs for creating an ekcp
- [x] docs for creating a concourse worker
- [x] move the ekcp project to SUSE
- [ ] document the decisions we've made and why we made them

**Comment by jimmykarily** [comment]
Problems we need to solve (or already solved):

- Tasks take too long to start. After lots of debugging, turns out it is a known (?) problem with the overlay baggageclaim driver and privileged containers. More here: https://github.com/cloudfoundry-incubator/kubecf/pull/885 . Removing the `privileged` setting, seems to fix the problem (it wan't needed anyway).

- Re triggering the pipeline for the same commit is a manual process (because next jobs won't trigger if the inputs haven't changed). We had [a custom resource](https://github.com/SUSE/concourse-git-queue) that solved this problem by creating a new version every time we triggered (a combination of the commit sha and a timestamp) but it seemed a bit too complex and confused people. We need to find a way to achieve the same in a simpler way.

- Testing clusters not cleaned up. This issue is tied to the previous one. If someone decide to trigger a new "deploy" job this will result in a new testing cluster. We only clean up clusters when a job fails or when the pipeline reaches the end. But given the issue above, the next jobs won't start and the cleanup task will never be triggered (unless someone manually keeps triggering one job after the other). Solving the above issue, will solve this one too.

**Comment by manno** [comment]
I started on the systemd unit for concourse workers, but I can't get the openstack heat scripts to work. I used ekcp worker heat templates as a start.

* https://gist.github.com/manno/091aef4d0e80ff92cec360eb40a32eba#file-openstack_concourse-yaml
* https://gist.github.com/manno/4594d6a67986a316757b8a1bcf6f16b1#file-openstack_concourse_stack-yaml

The systemd unit file was taken from the Concourse CI repo.

**Comment by jimmykarily** [comment]
CATs on Eirini fail because of this: https://github.com/cloudfoundry/cf-smoke-tests/pull/61/files

**Comment by mudler** [comment]
EKCP docs: https://github.com/SUSE/cloudfoundry/wiki/EKCP-Deployment#openstack-heat-template  https://github.com/mudler/ekcp/wiki/Deployment-setups

**Comment by viccuad** [comment]
https://github.com/SUSE/cloudfoundry/pull/168 closes:
- [ ] systemd unit to run a concourse worker
- [ ] heat template for concourse workers
- [ ] docs for creating a concourse worker

**Comment by jimmykarily** [comment]
We had random failures after we switched to GKE. This must have fixed it: https://github.com/cloudfoundry-incubator/kubecf/pull/991

**Comment by viccuad** [comment]
Opened https://github.com/cloudfoundry-incubator/kubecf/pull/1017 for that.

**Comment by viovanov** [comment]
CI seems to be more stable - closing this issue.
Any new problems should have specific issues opened.
